annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Resource Reconcile Interval Must Be Set Between Lower and
    Upper Bound
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/resource-reconcile-interval
  kubewarden/resources: HelmRelease, GitRepository, OCIRepository, Bucket, HelmChart,
    HelmRepository, Kustomization
  kubewarden/rules: |
    - apiGroups:
      - helm.toolkit.fluxcd.io
      apiVersions:
      - v2
      resources:
      - helmreleases
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - source.toolkit.fluxcd.io
      apiVersions:
      - v1
      resources:
      - gitrepositories
      - ocirepositories
      - buckets
      - helmcharts
      - helmrepositories
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - kustomize.toolkit.fluxcd.io
      apiVersions:
      - v1
      resources:
      - kustomizations
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.1
appVersion: 1.0.1
description: The reconcile interval of a Resource must be set between a lower and
  upper bound, lower_bound & upper_bound must be in seconds .
home: https://github.com/kubewarden/rego-policies-library
keywords:
- flux
name: resource-reconcile-interval
sources:
- ghcr.io/kubewarden/policies/resource-reconcile-interval:v1.0.1
version: 1.0.1
