annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Istio Gateway Approved Hosts
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/istio-gateway-approved-hosts
  kubewarden/resources: Gateway
  kubewarden/rules: |
    - apiGroups:
      - networking.istio.io
      apiVersions:
      - v1
      resources:
      - gateways
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.1
appVersion: 1.0.1
description: "### Istio Gateway Approved Hosts\nThis ensures you are only serving
  traffic for approved hostnames. \n"
home: https://github.com/kubewarden/rego-policies-library
name: istio-gateway-approved-hosts
sources:
- ghcr.io/kubewarden/policies/istio-gateway-approved-hosts:v1.0.1
version: 1.0.1
