annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Rbac Prohibit Wildcard On Secrets
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/rbac-prohibit-wildcard-secrets
  kubewarden/resources: Role, ClusterRole
  kubewarden/rules: |
    - apiGroups:
      - rbac.authorization.k8s.io
      apiVersions:
      - v1
      resources:
      - roles
      - clusterroles
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.1
appVersion: 1.0.1
description: |
  This Policy will violate if any RBAC ClusterRoles or Roles are designated with 'wildcard' verb on 'secrets' resource.
home: https://github.com/kubewarden/rego-policies-library
name: rbac-prohibit-wildcard-secrets
sources:
- ghcr.io/kubewarden/policies/rbac-prohibit-wildcard-secrets:v1.0.1
version: 1.0.1
