annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Namespace Resources Limitrange
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/namespace-resources-limitrange
  kubewarden/resources: LimitRange
  kubewarden/rules: |
    - apiGroups:
      - ''
      apiVersions:
      - v1
      resources:
      - limitranges
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.1
appVersion: 1.0.1
description: |
  When setting up default CPU and Memory values for your namespace, this policy will check if both requests and limits are set. This policy checks for the following:

  | Resource Setting | Resource Type  |
  |---|---|
  |  default | cpu  |
  |  default  | memory  |
  |  defaultRequest |  cpu |
  |  defaultRequest | memory  |
  |  min | memory  |
  |  min | cpu  |
  |  max | cpu |
  |  max | memory  |
home: https://github.com/kubewarden/rego-policies-library
keywords:
- soc2-type1
name: namespace-resources-limitrange
sources:
- ghcr.io/kubewarden/policies/namespace-resources-limitrange:v1.0.1
version: 1.0.1
