annotations:
  artifacthub.io/repository: kubewarden-rego-policies-library
  catalog.cattle.io/hidden: "true"
  catalog.cattle.io/type: kubewarden-policy
  catalog.cattle.io/ui-component: kubewarden
  kubewarden/displayName: Metadata Missing Label And Value
  kubewarden/mutation: "false"
  kubewarden/registry: ghcr.io
  kubewarden/repository: kubewarden/policies/metadata-missing-label-and-value
  kubewarden/resources: DaemonSet, Deployment, Job, StatefulSet
  kubewarden/rules: |
    - apiGroups:
      - apps
      apiVersions:
      - v1
      resources:
      - daemonsets
      - deployments
      - statefulsets
      operations:
      - CREATE
      - UPDATE
    - apiGroups:
      - batch
      apiVersions:
      - v1
      resources:
      - jobs
      operations:
      - CREATE
      - UPDATE
  kubewarden/tag: v1.0.1
appVersion: 1.0.1
description: "Custom labels can help enforce organizational standards for each artifact
  deployed. This Policy ensures a key and value are set in the entity's `metadata.labels`
  path. The Policy detects the presence of the following: \n\n### label\nA label key
  of your choosing. \n\n### value\nA label value of your choosing.\n"
home: https://github.com/kubewarden/rego-policies-library
name: metadata-missing-label-and-value
sources:
- ghcr.io/kubewarden/policies/metadata-missing-label-and-value:v1.0.1
version: 1.0.1
